version: '3'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch
    restart: always
    ports:
      - "9200:9200"

  kibana:
    container_name: kibana
    image: kibana
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
