version: '3'

services:
  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    ports:
      - "9200:9200"

  kibana:
    image: kibana
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
